### ISSUE TITLE
Conversion of issue links

### ISSUE THREAD

**Issue by fpoli** [viperproject/bitbucket-issue-migration#13]
The issues mentioned in the migration of [carbon issue 229](https://github.com/fpoli/viper-carbon/issues/229) are not recognized and converted to url. So, Github renders it differently depending on the order of creation of the issues. An example of the result:

> * issue #126
> * issue #132
> * issue #174
> * issue #220

**Comment by ArquintL** [comment]
The `IMPLICIT_ISSUE_LINK_RE` regex somehow did not match this - it looks like the `\i` flag (to enable case insensitivity) is not understood by re. Fixed in 861b080

**Comment by ArquintL** [comment]
"issue " should become optional (e.g. carbon #5) and the regex for pull requests has to be executed before that one

**Comment by ArquintL** [comment]
Done in fdb95dc

**Comment by ArquintL** [comment]
ab79741 improves the used regex to skip the following cases:
"carbon#5"
"silicon #12abc"

**Comment by fpoli** [comment]
There is still an issue with the regex. See this comment: https://github.com/fpoli/viper-carbon/issues/19#issuecomment-587383007

**Comment by ArquintL** [comment]
a whitespace is appended to URLs: 1d3626b3cc929f0c148e99d7f996d7120d9f7552
